prometheus:
  prometheusSpec:
    # Namespaces to be selected for PodMonitor discovery.
    # If nil, select own namespace.
    podMonitorNamespaceSelector: {}

    # PodMonitors to be selected for target discovery.
    # If {}, select all PodMonitors.
    podMonitorSelector: {}

    # If true, a nil or {} value for prometheus.prometheusSpec.podMonitorSelector will cause
    # the prometheus resource to be created with selectors based on values in the helm
    # deployment, which will also match the podmonitors created.
    podMonitorSelectorNilUsesHelmValues: false

    # Namespaces to be selected for ServiceMonitor discovery.
    serviceMonitorNamespaceSelector: {}
