apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: test

spec:
  imageName: docker.io/archismanmridha/custom-postgres:17.0

  instances: 1

  storage:
    size: 100Mi

  postgresql:
    shared_preload_libraries:
      - citus

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backups
        serverName: revision-1

  # Recover the cluster from existing incremental physical backups.
  bootstrap:
    recovery:
      source: test
  externalClusters:
    - name: test
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backups
          serverName: revision-0

  # monitoring:
  #   enablePodMonitor: true
